import { randomBytes, randomUUID } from "node:crypto";
import { createServer } from "node:http";
import { existsSync, rmSync } from "node:fs";
import path from "node:path";
import { MAX_BODY, PROTOCOL } from "./protocol.mjs";
import { atomicWrite, projectId } from "./state.mjs";

async function readBody(req) { const chunks = []; let size = 0; for await (const chunk of req) { size += chunk.length; if (size > MAX_BODY) throw new Error("Body exceeds 4 MiB"); chunks.push(chunk); } const value = chunks.length ? JSON.parse(Buffer.concat(chunks)) : {}; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Body must be object"); return value; }
function send(res, status, value) { if (value === undefined) { res.writeHead(status); res.end(); return; } const bytes = Buffer.from(JSON.stringify(value)); res.writeHead(status, { "content-type": "application/json", "content-length": bytes.length }); res.end(bytes); }
export class Coordinator {
  constructor({ stateRoot, timeoutMs = 120000 } = {}) { this.stateRoot = stateRoot; this.timeoutMs = timeoutMs; this.token = randomBytes(32).toString("base64url"); this.server = null; this.endpoint = null; this.connections = new Map(); this.queues = new Map(); this.pending = new Map(); this.runtimeFile = path.join(stateRoot, "runtime", `server-${process.pid}.json`); this.currentFile = path.join(stateRoot, "runtime", "current.json"); }
  key(file) { return path.resolve(file || "").toLowerCase(); }
  async start() { if (this.server) return this; this.server = createServer((req, res) => void this.handle(req, res)); await new Promise((resolve, reject) => { this.server.once("error", reject); this.server.listen(0, "127.0.0.1", resolve); }); this.endpoint = `http://127.0.0.1:${this.server.address().port}`; const record = { protocol: PROTOCOL, endpoint: this.endpoint, token: this.token, pid: process.pid, createdAt: new Date().toISOString() }; atomicWrite(this.runtimeFile, `${JSON.stringify(record, null, 2)}\n`); atomicWrite(this.currentFile, `${JSON.stringify(record, null, 2)}\n`); return this; }
  async close() { for (const item of this.pending.values()) item.reject(new Error("Coordinator stopped")); this.pending.clear(); if (this.server) await new Promise((resolve) => this.server.close(resolve)); this.server = null; for (const file of [this.runtimeFile, this.currentFile]) if (existsSync(file)) rmSync(file, { force: true }); }
  isConnected(file) { const item = this.connections.get(this.key(file)); return Boolean(item && Date.now() - item.lastSeen < 10000); }
  connection(file) { return this.connections.get(this.key(file)) || null; }
  disconnect(file) { this.connections.delete(this.key(file)); }
  async dispatch(file, operation, input = {}) { if (!this.isConnected(file)) throw new Error("Blender extension is not connected"); const requestId = randomUUID(); const key = this.key(file); const job = { protocol: PROTOCOL, requestId, projectId: projectId(file), projectFile: file, operation, input, deadline: new Date(Date.now() + this.timeoutMs).toISOString() }; const queue = this.queues.get(key) || []; queue.push(job); this.queues.set(key, queue); return await new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(requestId); reject(new Error(`Blender ${operation} timed out`)); }, this.timeoutMs); this.pending.set(requestId, { resolve, reject, timer, file }); }); }
  async handle(req, res) { try { if (req.headers.authorization !== `Bearer ${this.token}`) return send(res, 401, { error: "unauthorized" }); const url = new URL(req.url, this.endpoint); if (req.method === "POST" && url.pathname === "/v1/connect") { const body = await readBody(req); if (body.protocol !== PROTOCOL || typeof body.projectFile !== "string") return send(res, 400, { error: "invalid envelope" }); this.connections.set(this.key(body.projectFile), { ...body, lastSeen: Date.now() }); return send(res, 200, { accepted: true, projectId: projectId(body.projectFile), protocol: PROTOCOL }); } if (req.method === "GET" && url.pathname === "/v1/jobs/next") { const file = url.searchParams.get("projectFile"); const key = this.key(file); const conn = this.connections.get(key); if (conn) conn.lastSeen = Date.now(); const queue = this.queues.get(key) || []; const job = queue.shift(); this.queues.set(key, queue); return job ? send(res, 200, job) : send(res, 204); } const match = url.pathname.match(/^\/v1\/jobs\/([A-Za-z0-9-]+)\/complete$/); if (req.method === "POST" && match) { const body = await readBody(req); const pending = this.pending.get(match[1]); if (!pending) return send(res, 404, { error: "unknown job" }); this.pending.delete(match[1]); clearTimeout(pending.timer); pending.resolve(body); return send(res, 200, { accepted: true }); } return send(res, 404, { error: "not found" }); } catch (error) { return send(res, 400, { error: String(error.message).slice(0, 2000) }); } }
}
