import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { fileSha, resolveStateRoot, sha256, writeJson } from "./state.mjs";

const sourceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export function enginePath(raw) { const value = raw || process.env.BLENDER_ENGINE_PATH || "C:\\Program Files\\Blender Foundation\\Blender 5.2\\blender.exe"; const full = path.resolve(value); if (!existsSync(full) || !statSync(full).isFile()) throw new Error(`Blender executable not found: ${full}`); return full; }
export function inspectInstallation({ enginePath: raw } = {}) { const executable = enginePath(raw); const versionOutput = execFileSync(executable, ["--version"], { encoding: "utf8", timeout: 30000 }); const first = versionOutput.split(/\r?\n/)[0]; if (first !== "Blender 5.2.1 LTS") throw new Error(`Unsupported Blender build: ${first}`); return { status: "inspected", executable, sha256: fileSha(executable), version: first, buildHash: versionOutput.match(/build hash:\s*([^\r\n]+)/)?.[1]?.trim() || null, extensionCommands: true } }
function run(executable, args, cwd = sourceRoot) { const result = spawnSync(executable, args, { cwd, encoding: "utf8", timeout: 180000, windowsHide: true }); if (result.status !== 0) throw new Error(`Blender command failed (${result.status}): ${(result.stderr || result.stdout).slice(-4000)}`); return `${result.stdout || ""}${result.stderr || ""}`; }
export function installExtension({ enginePath: raw } = {}, runtime = {}) { const installation = inspectInstallation({ enginePath: raw }); const extension = path.join(sourceRoot, "blender-extension"); run(installation.executable, ["--command", "extension", "validate"], extension); const staging = path.join(runtime.stateRoot || resolveStateRoot(), "extension-builds", "0.2.0"); mkdirSync(staging, { recursive: true }); const archive = path.join(staging, "blender_bridge-0.2.0.zip"); if (existsSync(archive)) rmSync(archive, { force: true }); run(installation.executable, ["--command", "extension", "build", "--output-filepath", archive], extension); if (!existsSync(archive)) throw new Error("Blender extension build did not produce archive"); const userRoot = path.join(process.env.APPDATA || path.join(process.env.USERPROFILE, "AppData", "Roaming"), "Blender Foundation", "Blender", "5.2", "extensions", "user_default"); const prior = path.join(userRoot, "blender_bridge"); const priorState = existsSync(prior) ? { existed: true, digest: sha256(readdirSync(prior, { recursive: true }).sort()) } : { existed: false }; if (priorState.existed) throw new Error("Existing Blender Bridge extension must be removed through recorded ownership before replacement"); run(installation.executable, ["--command", "extension", "install-file", "-r", "user_default", "-e", archive], sourceRoot); if (!existsSync(prior)) throw new Error("Installed extension missing from user_default"); const record = { schema: "blender-bridge/extension-install/v1", installation, archive, archiveSha256: fileSha(archive), installedRoot: prior, priorState, installedAt: new Date().toISOString() }; writeJson(path.join(runtime.stateRoot || resolveStateRoot(), "extension", "installation.json"), record); return { status: "installed", ...record }; }
export function removeExtension({ enginePath: raw } = {}, runtime = {}) { const stateRoot = runtime.stateRoot || resolveStateRoot(); const recordFile = path.join(stateRoot, "extension", "installation.json"); if (!existsSync(recordFile)) return { status: "absent" }; const record = JSON.parse(readFileSync(recordFile, "utf8")); const installation = inspectInstallation({ enginePath: raw || record.installation.executable }); if (!existsSync(record.installedRoot)) return { status: "already-removed", priorState: record.priorState }; run(installation.executable, ["--command", "extension", "remove", "blender_bridge"], sourceRoot); if (existsSync(record.installedRoot)) throw new Error("Blender extension removal did not remove owned root"); return { status: "removed", priorState: record.priorState, installedRoot: record.installedRoot }; }
