#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { Coordinator } from "./coordinator.mjs";
import { inspectInstallation, installExtension, removeExtension } from "./installation.mjs";
import { applyTransaction, captureRender, captureViewport, closeOwnedBlender, enrollProject, exportArtifact, inspectProject, inspectRender, openProject, rollbackReceipt, startRender, stopRender, unenrollProject } from "./operations.mjs";
import { resolveStateRoot } from "./state.mjs";

const closed = { type: "object", additionalProperties: false };
const projectFile = { type: "string", description: "Absolute enrolled .blend file." };
const revision = { type: "string", pattern: "^sha256:[a-f0-9]{64}$" };
const outputPath = { type: "string", description: "Absolute absent final artifact outside the project directory." };
const transaction = JSON.parse(readFileSync(new URL("../schemas/transaction.schema.json", import.meta.url), "utf8")); delete transaction.$schema; delete transaction.$id;
export const TOOLS = [
  { name: "inspect_installation", description: "Inspect the exact Blender 5.2 executable version and hash.", inputSchema: { ...closed, properties: { enginePath: { type: "string" } } } },
  { name: "install_extension", description: "Validate, build, install, enable, and hash the owned Blender extension in user_default.", inputSchema: { ...closed, properties: { enginePath: { type: "string" } } } },
  { name: "remove_extension", description: "Remove only the recorded bridge-owned extension and restore prior state.", inputSchema: { ...closed, properties: { enginePath: { type: "string" } } } },
  { name: "enroll_project", description: "Bind one existing clean .blend to exact Blender and extension identity.", inputSchema: { ...closed, properties: { projectFile, enginePath: { type: "string" } }, required: ["projectFile"] } },
  { name: "unenroll_project", description: "Remove one enrollment without touching the .blend.", inputSchema: { ...closed, properties: { projectFile }, required: ["projectFile"] } },
  { name: "open_project", description: "Open an enrolled project in an owned Blender editor or background process.", inputSchema: { ...closed, properties: { projectFile, mode: { enum: ["editor", "background"] } }, required: ["projectFile"] } },
  { name: "close_owned_blender", description: "Close only a Blender process owned by this bridge.", inputSchema: { ...closed, properties: { projectFile }, required: ["projectFile"] } },
  { name: "inspect_project", description: "Return bounded native scene, dependency graph, material, animation, render, dirty, diagnostic, and revision evidence.", inputSchema: { ...closed, properties: { projectFile, limit: { type: "integer", minimum: 1, maximum: 500 }, cursor: { type: "string" } }, required: ["projectFile"] } },
  { name: "apply_transaction", description: "Apply one closed clean revision-guarded DCC transaction with checkpoint, readback, receipt, and automatic restoration.", inputSchema: transaction },
  { name: "start_render", description: "Start one owned revision-bound PNG render into safe staging.", inputSchema: { ...closed, properties: { projectFile, expectedRevision: revision, outputPath }, required: ["projectFile", "expectedRevision", "outputPath"] } },
  { name: "inspect_render", description: "Inspect bounded logs and status for one owned render.", inputSchema: { ...closed, properties: { renderId: { type: "string" }, cursor: { type: ["string", "integer"] } }, required: ["renderId"] } },
  { name: "capture_render", description: "Return the verified PNG and hashes for a completed owned render.", inputSchema: { ...closed, properties: { renderId: { type: "string" } }, required: ["renderId"] } },
  { name: "stop_render", description: "Cancel only one bridge-owned render process.", inputSchema: { ...closed, properties: { renderId: { type: "string" } }, required: ["renderId"] } },
  { name: "capture_viewport", description: "Capture a live 3D viewport when available or deterministic offscreen PNG otherwise.", inputSchema: { ...closed, properties: { projectFile, expectedRevision: revision, outputPath, width: { type: "integer", minimum: 64, maximum: 4096 }, height: { type: "integer", minimum: 64, maximum: 4096 } }, required: ["projectFile", "expectedRevision", "outputPath"] } },
  { name: "export_artifact", description: "Export revision-bound GLB, FBX, USD, OBJ, or Alembic through closed options and verified promotion.", inputSchema: { ...closed, properties: { projectFile, expectedRevision: revision, format: { enum: ["glb", "fbx", "usd", "obj", "alembic"] }, outputPath, options: { type: "object", additionalProperties: false, properties: { selectedOnly: { type: "boolean" }, animation: { type: "boolean" }, materials: { type: "boolean" }, extras: { type: "boolean", description: "GLB only: include semantic custom properties." }, start: { type: "integer" }, end: { type: "integer" } } } }, required: ["projectFile", "expectedRevision", "format", "outputPath"] } },
  { name: "rollback_receipt", description: "Restore exact receipt-bound pre-state and independently verify identity.", inputSchema: { ...closed, properties: { receiptId: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" } }, required: ["receiptId"] } }
];

const defaultRuntime = { stateRoot: resolveStateRoot(), processes: new Map(), jobs: new Map(), writes: new Map() };
defaultRuntime.coordinator = new Coordinator({ stateRoot: defaultRuntime.stateRoot });
const handlers = { inspect_installation: inspectInstallation, install_extension: installExtension, remove_extension: removeExtension, enroll_project: enrollProject, unenroll_project: unenrollProject, open_project: openProject, close_owned_blender: closeOwnedBlender, inspect_project: inspectProject, apply_transaction: applyTransaction, start_render: startRender, inspect_render: inspectRender, capture_render: captureRender, stop_render: stopRender, capture_viewport: captureViewport, export_artifact: exportArtifact, rollback_receipt: rollbackReceipt };
function error(id, code, message) { return { jsonrpc: "2.0", id: id ?? null, error: { code, message: String(message).slice(0, 2000) } }; }
export async function handleRpc(message, runtime = defaultRuntime) { if (!message || message.jsonrpc !== "2.0" || typeof message.method !== "string") return error(message?.id, -32600, "Invalid Request"); if (message.method === "notifications/initialized" || message.method === "notifications/cancelled") return null; if (message.method === "initialize") return { jsonrpc: "2.0", id: message.id, result: { protocolVersion: message.params?.protocolVersion || "2025-06-18", capabilities: { tools: {} }, serverInfo: { name: "blender-bridge", title: "Blender Bridge", version: "0.3.0" } } }; if (message.method === "ping") return { jsonrpc: "2.0", id: message.id, result: {} }; if (message.method === "tools/list") return { jsonrpc: "2.0", id: message.id, result: { tools: TOOLS } }; if (message.method !== "tools/call") return error(message.id, -32601, "Method not found"); const handler = handlers[message.params?.name]; if (!handler) return error(message.id, -32602, "Unknown tool"); try { await runtime.coordinator?.start(); const result = await handler(message.params?.arguments || {}, runtime); const content = []; if (result?.pngBase64) content.push({ type: "image", data: result.pngBase64, mimeType: "image/png" }); content.push({ type: "text", text: JSON.stringify(result) }); return { jsonrpc: "2.0", id: message.id, result: { content, structuredContent: result, isError: ["rejected", "rolled-back", "manual-recovery-required"].includes(result?.status) } }; } catch (caught) { const result = { status: "rejected", error: String(caught.message).slice(0, 2000) }; return { jsonrpc: "2.0", id: message.id, result: { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result, isError: true } }; } }
export async function startStdio(runtime = defaultRuntime) { await runtime.coordinator?.start(); let buffer = ""; process.stdin.setEncoding("utf8"); process.stdin.on("data", (chunk) => { buffer += chunk; while (true) { const newline = buffer.indexOf("\n"); if (newline < 0) break; const line = buffer.slice(0, newline).replace(/\r$/, ""); buffer = buffer.slice(newline + 1); if (!line.trim()) continue; void (async () => { let response; try { response = await handleRpc(JSON.parse(line), runtime); } catch (caught) { response = error(null, -32700, `Parse error: ${caught.message}`); } if (response) process.stdout.write(`${JSON.stringify(response)}\n`); })(); } }); const cleanup = () => void runtime.coordinator?.close(); process.once("exit", cleanup); process.once("SIGINT", cleanup); process.once("SIGTERM", cleanup); }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await startStdio();
