import { createHash, randomUUID } from "node:crypto";
import { chmodSync, copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, renameSync, rmSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

export const PLUGIN_VERSION = "0.3.0";
export function stable(value) { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`; return JSON.stringify(value); }
export function sha256(value) { return createHash("sha256").update(Buffer.isBuffer(value) ? value : Buffer.from(typeof value === "string" ? value : stable(value))).digest("hex"); }
export function fileSha(file) { return sha256(readFileSync(file)); }
export function revision(file) { return `sha256:${fileSha(file)}`; }
export function resolveStateRoot(override) { const home = override || process.env.CODEX_HOME || path.join(os.homedir(), ".codex"); return path.join(path.resolve(home), "state", "plugins", "blender-bridge", "v1"); }
export function atomicWrite(file, bytes, immutable = false) { mkdirSync(path.dirname(file), { recursive: true }); const data = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes); if (immutable && existsSync(file)) { if (!readFileSync(file).equals(data)) throw new Error(`Immutable collision: ${file}`); return; } const tmp = path.join(path.dirname(file), `.${path.basename(file)}.${process.pid}.${randomUUID()}.tmp`); try { writeFileSync(tmp, data, { flag: "wx", mode: 0o600 }); try { chmodSync(tmp, 0o600); } catch {} renameSync(tmp, file); } finally { if (existsSync(tmp)) unlinkSync(tmp); } }
export function writeJson(file, value, immutable = false) { atomicWrite(file, `${JSON.stringify(value, null, 2)}\n`, immutable); return value; }
function noLinks(target) { const parsed = path.parse(target); let current = parsed.root; for (const part of target.slice(parsed.root.length).split(path.sep).filter(Boolean)) { current = path.join(current, part); if (existsSync(current) && lstatSync(current).isSymbolicLink()) throw new Error(`Symlink/reparse traversal rejected: ${current}`); } }
export function resolveProjectFile(raw) { if (typeof raw !== "string" || !path.isAbsolute(raw)) throw new Error("projectFile must be absolute"); const full = realpathSync.native(path.resolve(raw)); noLinks(full); if (!statSync(full).isFile() || path.extname(full).toLowerCase() !== ".blend") throw new Error("projectFile must be an existing .blend file"); return full; }
export function projectId(file) { return `sha256:${sha256(path.resolve(file).toLowerCase())}`; }
export function enrollmentPath(root, file) { return path.join(root, "enrollments", `${projectId(file).slice(7)}.json`); }
export function readEnrollment(root, file) { const target = enrollmentPath(root, file); if (!existsSync(target)) throw new Error("Project is not enrolled in Blender Bridge"); return { file: target, enrollment: JSON.parse(readFileSync(target, "utf8")) }; }
export function recoveryPath(root, file) { return path.join(root, "recovery", `${projectId(file).slice(7)}.json`); }
export function assertRecoveryClear(root, file) { const target = recoveryPath(root, file); if (existsSync(target) && JSON.parse(readFileSync(target, "utf8")).state === "manual-recovery-required") throw new Error("Project requires manual recovery before writes"); }
export function checkpoint(root, projectFile, externalWrites = [], transactionId = randomUUID()) { const files = [projectFile, ...externalWrites].map((item) => path.resolve(item)); const id = sha256({ projectFile, files, transactionId, nonce: randomUUID() }); const base = path.join(root, "checkpoints", id); mkdirSync(path.join(base, "files"), { recursive: true }); const entries = files.map((file, index) => { noLinks(path.dirname(file)); const existed = existsSync(file); if (existed) copyFileSync(file, path.join(base, "files", `${index}.bin`)); return { file, existed, sha256: existed ? fileSha(file) : null, stored: existed ? `${index}.bin` : null }; }); writeJson(path.join(base, "index.json"), { schema: "blender-bridge/checkpoint/v1", checkpointId: `sha256:${id}`, projectFile, entries }, true); return { checkpointId: `sha256:${id}`, base, entries }; }
export function restoreCheckpoint(root, checkpointId) { if (!/^sha256:[a-f0-9]{64}$/.test(checkpointId || "")) throw new Error("Invalid checkpointId"); const base = path.join(root, "checkpoints", checkpointId.slice(7)); const index = JSON.parse(readFileSync(path.join(base, "index.json"), "utf8")); for (const entry of index.entries) { if (entry.existed) atomicWrite(entry.file, readFileSync(path.join(base, "files", entry.stored))); else if (existsSync(entry.file)) rmSync(entry.file, { force: true }); } return index; }
export function sealReceipt(root, body, kind = "receipt") { const clean = { ...body, schema: `blender-bridge/${kind}/v1`, pluginVersion: PLUGIN_VERSION }; const digest = sha256(clean); const receipt = { ...clean, receiptId: `sha256:${digest}` }; const folder = kind === "receipt" ? "receipts" : `${kind}-receipts`; const file = path.join(root, folder, `${digest}.json`); writeJson(file, receipt, true); return { receipt, file }; }
export function readReceipt(root, id) { if (!/^sha256:[a-f0-9]{64}$/.test(id || "")) throw new Error("receiptId must be sha256:<64 lowercase hex>"); const file = path.join(root, "receipts", `${id.slice(7)}.json`); if (!existsSync(file)) throw new Error("Unknown Blender Bridge receipt"); const receipt = JSON.parse(readFileSync(file, "utf8")); if (receipt.receiptId !== id || `sha256:${sha256(Object.fromEntries(Object.entries(receipt).filter(([key]) => key !== "receiptId")))}` !== id) throw new Error("Receipt identity mismatch"); return { receipt, file }; }
export function resolveExternalOutput(projectFile, output) { if (typeof output !== "string" || !path.isAbsolute(output)) throw new Error("outputPath must be absolute"); const final = path.resolve(output); if (existsSync(final)) throw new Error("Final artifact already exists"); noLinks(path.dirname(final)); const projectDir = `${path.dirname(projectFile)}${path.sep}`.toLowerCase(); if (`${final}${path.sep}`.toLowerCase().startsWith(projectDir)) throw new Error("Output must be outside the project directory"); if (!existsSync(path.dirname(final)) || !statSync(path.dirname(final)).isDirectory()) throw new Error("Output directory must exist"); return final; }
